version: '3.2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  postgres:
      image: postgres:14.2-alpine
      restart: always
      expose:
          - "5432"
      environment:
          POSTGRES_PASSWORD: examplePassword
          POSTGRES_USER: exampleUser
          POSTGRES_DB: exampleDB
      volumes:
          - ./postgresql/data:/var/lib/postgresql/data
      stdin_open: true # docker run -i
      tty: true        # docker run -t

  real-nginx:
      image: nicolasbiondini/nginx-backend-ui:v1.0.0
      container_name: real-nginx
      expose:
        - "80"
      restart: always
      environment:
        - VIRTUAL_HOST=beatapp.live,www.beatapp.live
        - LETSENCRYPT_HOST=beatapp.live,www.beatapp.live
        - LETSENCRYPT_EMAIL=example@email.com
      depends_on:
        - nginx-proxy
        - letsencrypt

  backend:
      image: nicolasbiondini/backend-beatapp:v1.0.1
      environment:
          PORT: 3001
          JWT_SECRET: "exampleToken"
          JWT_REFRESH_SECRET: "exampleRefreshToken"
          USER: "exampleUser"
          HOST: "postgres"
          PASSWORD: "examplePassword"
          DATABASE: "exampleDB"
          DB_PORT: 5432
      container_name: "backend"
      expose:
         - "3001"
  ui:
      image: nicolasbiondini/ui:v1.0.2
      container_name: ui
      expose:
         - "3000"
      depends_on:
         - real-nginx

volumes:
  certs:
  html:
  vhostd:


